Feature add remove
NatanimA/To-Do-List-App pull request #3
Opened 2022-09-29 20:00 UTC by NatanimA

> Inserted Todo list project structure

> Inserted Add and Remove functions

> Inserted Line-through checker

> Inserted Edit function

> Removal by Selection only by pressing the trash button currently as the requirement

> Followed Html and CSS best practices

> Inserted webpack and loaders to the project

> Fetching of data dynamically by Javascript objects

`Please do this to run it on your pc`

`npm start` =>this will prompt you to install webpack then `y` and it will install

`npm run build` => this will generate codes to the dist folder

`npm start` and this will start the server and you can see the the project I did 😉

2022-09-29 21:14 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Natanim, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
GitHub flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-29 21:14 UTC, SajjadAhmad14 commented on src/index.js
> +
Please add a function for editing task descriptions. Currently, the user is not able to edit the task and on refresh, it's the same old task item.

2022-09-29 21:14 UTC, SajjadAhmad14 commented on src/modules/createTasks.js
> +            localData[i].completed = true;
User when checking an item the `completed` value doe not become `true` in local storage. Kindly make sure that the value gets `true` on checked and `false` on unchecked.

2022-09-29 21:39 UTC, merged

2022-09-30 08:15 UTC, GzimAsani reviewed
Hi @NatanimA , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already been merged. I understand that you did that by mistake, but please open new PR and leave the link for this old PR where the next reviewer can see the required changes asked by the previous reviewer

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-30 08:41 UTC, EricMbouwe reviewed
Hi @NatanimA, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Requested changes ✔
- Linters ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._